from oort.shared.errors import OortCloudError


class UploadPreparationError(OortCloudError):
    pass
